const data = {
    products: [
      {
        _id: '1',
        name: 'Vintage Camera',
        category: 'Shirts',
        image: '/images/camera.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nikon',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'VW Beetle',
        category: 'Shirts',
        image: '/images/car.jpg',
        price: 100,
        countInStock: 20,
        brand: 'Volks Wagon',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Espresso Beans',
        category: 'Shirts',
        image: '/images/coffee.jpg',
        price: 220,
        countInStock: 0,
        brand: 'X',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'No9 Cologne',
        category: 'Pants',
        image: '/images/cologne.jpg',
        price: 78,
        countInStock: 15,
        brand: 'No9',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Cupcake',
        category: 'Pants',
        image: '/images/cupcake.jpg',
        price: 65,
        countInStock: 5,
        brand: 'Yum',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Cool Pack',
        category: 'Pants',
        image: '/images/pack.jpg',
        price: 139,
        countInStock: 12,
        brand: 'Cool',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
      {
        _id: '7',
        name: 'FlowHeels',
        category: 'Pants',
        image: '/images/shoes.jpg',
        price: 139,
        countInStock: 12,
        brand: 'Flow Heels',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
      {
        _id: '8',
        name: 'Cute Plant',
        category: 'Pants',
        image: '/images/succulent.jpg',
        price: 139,
        countInStock: 12,
        brand: 'Simple',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
    ],
  };
  export default data;